### ISSUE TITLE
./install.sh: line 8: jq: command not found

### ISSUE THREAD

**Issue by whoami15** [liamg/gitjacker#3]
I tried installing but it shows an error

`./install.sh: line 8: jq: command not found`

**Comment by renjinsk** [comment]
> I tried installing but it shows an error
> 
> `./install.sh: line 8: jq: command not found`

You are missing a package from your system, to install it just run:
`sudo apt update && sudo apt install -y jq`

**Comment by AgnellusX1** [comment]
I successfully installed the latest version of the package jq
When trying to install it shows the error

`jq: error (at <stdin>:1): Cannot iterate over null (null)`

**Comment by Mou-Ikkai** [comment]
It works for me on Linux Mint 20

**Comment by mvarunsai** [comment]
how to get this tool on windows machine? I have cloned the repository but dont know how to install.Please help
